import { Link } from "react-router-dom";

export default function TermsAndConditions() {
  // Set page title
  document.title = "Terms and Conditions | Brown Hues";
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-3xl font-bold mb-8">Terms and Conditions</h1>
      
      <div className="prose prose-lg max-w-none">
        <p className="text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>

        <div className="space-y-6">
          <section>
            <p>
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name brownhues.in ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Platform Owner</h2>
            <p>
              The Platform is owned by SHIKHA PRIYADARSHANI, a company incorporated under the Companies Act, 1956 with its registered office at Carmelram, Bangalore, India (hereinafter referred to as "Platform Owner", 'we', 'us', 'our').
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Acceptance of Terms</h2>
            <p>
              Your use of the Platform and services and tools are governed by the following terms and conditions ('Terms of Use') as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').
            </p>
          </section>

          {/* Additional sections can be added here */}
          
          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
            <p>
              If you have any questions about these Terms and Conditions, please contact us at:
            </p>
            <address className="not-italic mt-2">
              SHIKHA PRIYADARSHANI<br />
              Carmelram, Bangalore, India<br />
              Email: [Your Contact Email]<br />
              Phone: [Your Contact Number]
            </address>
          </section>
        </div>
      </div>

      <div className="mt-12 pt-6 border-t border-border">
        <Link to="/" className="text-primary hover:underline">
          &larr; Back to Home
        </Link>
      </div>
    </div>
  );
}
