import {
  Box,
  LayoutDashboard,
  Package,
  ShoppingCart,
  Users,
  Settings,
  LogOut,
  ChevronDown,
  ChevronRight,
  Plus,
  Search,
  Filter,
  MoreHorizontal,
  Check,
  X,
  ArrowUpDown,
  Eye,
  Pencil,
  Trash2,
  ChevronLeft,
  ChevronFirst,
  ChevronLast,
  ChevronsLeft,
  ChevronsRight,
  Loader2,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  AlertTriangle,
  Menu,
  Home,
  User,
  DollarSign,
  Calendar,
  Clock,
  Tag,
  CreditCard,
  Truck,
  Package2,
  Bell,
  MessageSquare,
  Mail,
  Star,
  Heart,
  Share2,
  Download,
  Upload,
  FileText,
  Image,
  Sliders,
  Grid,
  List,
  Columns,
  BarChart2,
  PieChart,
  LineChart,
  Table,
  Database,
  Server,
  HardDrive,
  Cpu,
  Memory,
  Network,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Battery,
  BatteryCharging,
  Power,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudSleet,
  CloudSun,
  CloudMoon,
  Umbrella,
  Droplet,
  Wind,
  Thermometer,
  Compass,
  Navigation,
  MapPin,
  Map,
  Globe,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  User as UserIcon,
  Mail as MailIcon,
  Phone,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  Bell as BellIcon,
  Check as CheckIcon,
  X as XIcon,
  AlertTriangle as AlertTriangleIcon,
  AlertCircle as AlertCircleIcon,
  Info as InfoIcon,
  HelpCircle,
  Lock,
  Unlock,
  Eye as EyeIcon,
  EyeOff,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Bookmark,
  BookmarkCheck,
  BookOpen,
  Book,
  Briefcase,
  Camera,
  Coffee,
  CreditCard as CreditCardIcon,
  File as FileIcon,
  FileText as FileTextIcon,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileSearch,
  FileInput,
  FileOutput,
  FileSpreadsheet,
  FileCode,
  FileArchive,
  FileAudio,
  FileVideo,
  FileImage,
  FilePdf,
  FileWord,
  FileExcel,
  FilePowerPoint,
  Folder,
  FolderPlus,
  FolderMinus,
  FolderCheck,
  FolderX,
  FolderSearch,
  FolderInput,
  FolderOutput,
  FolderGit,
  FolderGit2,
  FolderSymlink,
  FolderRoot,
  FolderOpen,
  FolderTree,
  HardDrive as HardDriveIcon,
  HardDriveUpload,
  HardDriveDownload,
  HardDriveNetwork,
  HardDriveNetwork2,
  HardDriveCloud,
  HardDriveCloud2,
  HardDriveExternal,
  HardDriveInternal,
  HardDriveRemove,
  HardDriveAdd,
  HardDriveCheck,
  HardDriveX,
  HardDriveFormat,
  HardDriveDefrag,
  HardDriveScan,
  HardDriveShred,
  HardDriveBackup,
  HardDriveRestore,
  HardDriveServer,
  HardDriveServer2,
  HardDriveRaid,
  HardDriveRaid0,
  HardDriveRaid1,
  HardDriveRaid5,
  HardDriveRaid6,
  HardDriveRaid10,
  HardDriveRaid50,
  HardDriveRaid60,
  HardDriveRaidArray,
  HardDriveRaidArray2,
  HardDriveRaidArray3,
  HardDriveRaidArray4,
  HardDriveRaidArray5,
  HardDriveRaidArray6,
  HardDriveRaidArray7,
  HardDriveRaidArray8,
  HardDriveRaidArray9,
  HardDriveRaidArray10,
  HardDriveRaidArray11,
  HardDriveRaidArray12,
  HardDriveRaidArray13,
  HardDriveRaidArray14,
  HardDriveRaidArray15,
  HardDriveRaidArray16,
  HardDriveRaidArray17,
  HardDriveRaidArray18,
  HardDriveRaidArray19,
  HardDriveRaidArray20,
  HardDriveRaidArray21,
  HardDriveRaidArray22,
  HardDriveRaidArray23,
  HardDriveRaidArray24,
  HardDriveRaidArray25,
  HardDriveRaidArray26,
  HardDriveRaidArray27,
  HardDriveRaidArray28,
  HardDriveRaidArray29,
  HardDriveRaidArray30,
  HardDriveRaidArray31,
  HardDriveRaidArray32,
  HardDriveRaidArray33,
  HardDriveRaidArray34,
  HardDriveRaidArray35,
  HardDriveRaidArray36,
  HardDriveRaidArray37,
  HardDriveRaidArray38,
  HardDriveRaidArray39,
  HardDriveRaidArray40,
  HardDriveRaidArray41,
  HardDriveRaidArray42,
  HardDriveRaidArray43,
  HardDriveRaidArray44,
  HardDriveRaidArray45,
  HardDriveRaidArray46,
  HardDriveRaidArray47,
  HardDriveRaidArray48,
  HardDriveRaidArray49,
  HardDriveRaidArray50,
  HardDriveRaidArray51,
  HardDriveRaidArray52,
  HardDriveRaidArray53,
  HardDriveRaidArray54,
  HardDriveRaidArray55,
  HardDriveRaidArray56,
  HardDriveRaidArray57,
  HardDriveRaidArray58,
  HardDriveRaidArray59,
  HardDriveRaidArray60,
  HardDriveRaidArray61,
  HardDriveRaidArray62,
  HardDriveRaidArray63,
  HardDriveRaidArray64,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  logo: Package2,
  dashboard: LayoutDashboard,
  orders: ShoppingCart,
  products: Package,
  customers: Users,
  settings: Settings,
  logout: LogOut,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronFirst: ChevronFirst,
  chevronLast: ChevronLast,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  plus: Plus,
  search: Search,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  check: Check,
  x: X,
  arrowUpDown: ArrowUpDown,
  eye: Eye,
  pencil: Pencil,
  trash: Trash2,
  loader: Loader2,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  info: Info,
  alertTriangle: AlertTriangle,
  menu: Menu,
  home: Home,
  user: User,
  dollarSign: DollarSign,
  calendar: Calendar,
  clock: Clock,
  tag: Tag,
  creditCard: CreditCard,
  truck: Truck,
  package: Package2,
  bell: Bell,
  messageSquare: MessageSquare,
  mail: Mail,
  star: Star,
  heart: Heart,
  share2: Share2,
  download: Download,
  upload: Upload,
  fileText: FileText,
  image: Image,
  sliders: Sliders,
  grid: Grid,
  list: List,
  columns: Columns,
  barChart: BarChart2,
  pieChart: PieChart,
  lineChart: LineChart,
  table: Table,
  database: Database,
  server: Server,
  hardDrive: HardDrive,
  cpu: Cpu,
  memory: Memory,
  network: Network,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  bluetoothOff: BluetoothOff,
  battery: Battery,
  batteryCharging: BatteryCharging,
  power: Power,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  cloudDrizzle: CloudDrizzle,
  cloudFog: CloudFog,
  cloudHail: CloudHail,
  cloudSleet: CloudSleet,
  cloudSun: CloudSun,
  cloudMoon: CloudMoon,
  umbrella: Umbrella,
  droplet: Droplet,
  wind: Wind,
  thermometer: Thermometer,
  compass: Compass,
  navigation: Navigation,
  mapPin: MapPin,
  map: Map,
  globe: Globe,
  clockIcon: ClockIcon,
  calendarIcon: CalendarIcon,
  userIcon: UserIcon,
  mailIcon: MailIcon,
  phone: Phone,
  messageCircle: MessageCircle,
  messageSquareIcon: MessageSquareIcon,
  bellIcon: BellIcon,
  checkIcon: CheckIcon,
  xIcon: XIcon,
  alertTriangleIcon: AlertTriangleIcon,
  alertCircleIcon: AlertCircleIcon,
  infoIcon: InfoIcon,
  helpCircle: HelpCircle,
  lock: Lock,
  unlock: Unlock,
  eyeIcon: EyeIcon,
  eyeOff: EyeOff,
  starIcon: StarIcon,
  heartIcon: HeartIcon,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
  angry: Angry,
  bookmark: Bookmark,
  bookmarkCheck: BookmarkCheck,
  bookOpen: BookOpen,
  book: Book,
  briefcase: Briefcase,
  camera: Camera,
  coffee: Coffee,
  creditCardIcon: CreditCardIcon,
  fileIcon: FileIcon,
  fileTextIcon: FileTextIcon,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileCheck: FileCheck,
  fileX: FileX,
  fileSearch: FileSearch,
  fileInput: FileInput,
  fileOutput: FileOutput,
  fileSpreadsheet: FileSpreadsheet,
  fileCode: FileCode,
  fileArchive: FileArchive,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileImage: FileImage,
  filePdf: FilePdf,
  fileWord: FileWord,
  fileExcel: FileExcel,
  filePowerPoint: FilePowerPoint,
  folder: Folder,
  folderPlus: FolderPlus,
  folderMinus: FolderMinus,
  folderCheck: FolderCheck,
  folderX: FolderX,
  folderSearch: FolderSearch,
  folderInput: FolderInput,
  folderOutput: FolderOutput,
  folderGit: FolderGit,
  folderGit2: FolderGit2,
  folderSymlink: FolderSymlink,
  folderRoot: FolderRoot,
  folderOpen: FolderOpen,
  folderTree: FolderTree,
  hardDriveIcon: HardDriveIcon,
  hardDriveUpload: HardDriveUpload,
  hardDriveDownload: HardDriveDownload,
  hardDriveNetwork: HardDriveNetwork,
  hardDriveNetwork2: HardDriveNetwork2,
  hardDriveCloud: HardDriveCloud,
  hardDriveCloud2: HardDriveCloud2,
  hardDriveExternal: HardDriveExternal,
  hardDriveInternal: HardDriveInternal,
  hardDriveRemove: HardDriveRemove,
  hardDriveAdd: HardDriveAdd,
  hardDriveCheck: HardDriveCheck,
  hardDriveX: HardDriveX,
  hardDriveFormat: HardDriveFormat,
  hardDriveDefrag: HardDriveDefrag,
  hardDriveScan: HardDriveScan,
  hardDriveShred: HardDriveShred,
  hardDriveBackup: HardDriveBackup,
  hardDriveRestore: HardDriveRestore,
  hardDriveServer: HardDriveServer,
  hardDriveServer2: HardDriveServer2,
  hardDriveRaid: HardDriveRaid,
  hardDriveRaid0: HardDriveRaid0,
  hardDriveRaid1: HardDriveRaid1,
  hardDriveRaid5: HardDriveRaid5,
  hardDriveRaid6: HardDriveRaid6,
  hardDriveRaid10: HardDriveRaid10,
  hardDriveRaid50: HardDriveRaid50,
  hardDriveRaid60: HardDriveRaid60,
  hardDriveRaidArray: HardDriveRaidArray,
  hardDriveRaidArray2: HardDriveRaidArray2,
  hardDriveRaidArray3: HardDriveRaidArray3,
  hardDriveRaidArray4: HardDriveRaidArray4,
  hardDriveRaidArray5: HardDriveRaidArray5,
  hardDriveRaidArray6: HardDriveRaidArray6,
  hardDriveRaidArray7: HardDriveRaidArray7,
  hardDriveRaidArray8: HardDriveRaidArray8,
  hardDriveRaidArray9: HardDriveRaidArray9,
  hardDriveRaidArray10: HardDriveRaidArray10,
  hardDriveRaidArray11: HardDriveRaidArray11,
  hardDriveRaidArray12: HardDriveRaidArray12,
  hardDriveRaidArray13: HardDriveRaidArray13,
  hardDriveRaidArray14: HardDriveRaidArray14,
  hardDriveRaidArray15: HardDriveRaidArray15,
  hardDriveRaidArray16: HardDriveRaidArray16,
  hardDriveRaidArray17: HardDriveRaidArray17,
  hardDriveRaidArray18: HardDriveRaidArray18,
  hardDriveRaidArray19: HardDriveRaidArray19,
  hardDriveRaidArray20: HardDriveRaidArray20,
  hardDriveRaidArray21: HardDriveRaidArray21,
  hardDriveRaidArray22: HardDriveRaidArray22,
  hardDriveRaidArray23: HardDriveRaidArray23,
  hardDriveRaidArray24: HardDriveRaidArray24,
  hardDriveRaidArray25: HardDriveRaidArray25,
  hardDriveRaidArray26: HardDriveRaidArray26,
  hardDriveRaidArray27: HardDriveRaidArray27,
  hardDriveRaidArray28: HardDriveRaidArray28,
  hardDriveRaidArray29: HardDriveRaidArray29,
  hardDriveRaidArray30: HardDriveRaidArray30,
  hardDriveRaidArray31: HardDriveRaidArray31,
  hardDriveRaidArray32: HardDriveRaidArray32,
  hardDriveRaidArray33: HardDriveRaidArray33,
  hardDriveRaidArray34: HardDriveRaidArray34,
  hardDriveRaidArray35: HardDriveRaidArray35,
  hardDriveRaidArray36: HardDriveRaidArray36,
  hardDriveRaidArray37: HardDriveRaidArray37,
  hardDriveRaidArray38: HardDriveRaidArray38,
  hardDriveRaidArray39: HardDriveRaidArray39,
  hardDriveRaidArray40: HardDriveRaidArray40,
  hardDriveRaidArray41: HardDriveRaidArray41,
  hardDriveRaidArray42: HardDriveRaidArray42,
  hardDriveRaidArray43: HardDriveRaidArray43,
  hardDriveRaidArray44: HardDriveRaidArray44,
  hardDriveRaidArray45: HardDriveRaidArray45,
  hardDriveRaidArray46: HardDriveRaidArray46,
  hardDriveRaidArray47: HardDriveRaidArray47,
  hardDriveRaidArray48: HardDriveRaidArray48,
  hardDriveRaidArray49: HardDriveRaidArray49,
  hardDriveRaidArray50: HardDriveRaidArray50,
  hardDriveRaidArray51: HardDriveRaidArray51,
  hardDriveRaidArray52: HardDriveRaidArray52,
  hardDriveRaidArray53: HardDriveRaidArray53,
  hardDriveRaidArray54: HardDriveRaidArray54,
  hardDriveRaidArray55: HardDriveRaidArray55,
  hardDriveRaidArray56: HardDriveRaidArray56,
  hardDriveRaidArray57: HardDriveRaidArray57,
  hardDriveRaidArray58: HardDriveRaidArray58,
  hardDriveRaidArray59: HardDriveRaidArray59,
  hardDriveRaidArray60: HardDriveRaidArray60,
  hardDriveRaidArray61: HardDriveRaidArray61,
  hardDriveRaidArray62: HardDriveRaidArray62,
  hardDriveRaidArray63: HardDriveRaidArray63,
  hardDriveRaidArray64: HardDriveRaidArray64,
} as const;

export type IconName = keyof typeof Icons;
