// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byjojptmkvsjvtdxudxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5am9qcHRta3ZzanZ0ZHh1ZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTUxNzksImV4cCI6MjA2MDkzMTE3OX0.cSOaMn9pSidCTErc1tJOBehBZ4JMB2qXROEhoVp-iS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);